/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class operations_EmgNative */

#ifndef _Included_operations_EmgNative
#define _Included_operations_EmgNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     operations_EmgNative
 * Method:    filterChannel
 * Signature: ([DIDIIZ)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_operations_EmgNative_filterChannel
  (JNIEnv *, jobject, jdoubleArray, jint, jdouble, jint, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
